### ISSUE TITLE
Interestingness no longer works - Javascript error

### ISSUE THREAD

**Issue by pavellishin** [angst/moreinterestingness#2]
Javascript error appears under new tab, and no image is loaded:

```
Uncaught TypeError: Cannot read property 'src' of undefined
chrome-extension://ngddmdmkjnnefgggjnnnepijkcighifa/newtab.html:11
```

(Oddly enough, the source code in my extension does not match what's in the github repo:

Repo: https://github.com/angst/moreinterestingness/blob/master/newtab.html#L11
Me: `$("#photo").attr("src", photo.src);`
)

Ghostery is enabled and blocks Google tracking, but I've been running it for awhile, and it hasn't been a problem before.

Running Chrome Version 35.0.1916.153

![screen shot 2014-07-14 at 11 21 18](https://cloud.githubusercontent.com/assets/296084/3572720/a565ae0e-0b6a-11e4-8818-262cbf70622a.png)
![screen shot 2014-07-14 at 11 21 21](https://cloud.githubusercontent.com/assets/296084/3572719/a56584ec-0b6a-11e4-89e1-429911750900.png)
![screen shot 2014-07-14 at 11 21 26](https://cloud.githubusercontent.com/assets/296084/3572721/a565a8c8-0b6a-11e4-9b49-6239695b39f0.png)

**Comment by jakedahn** [comment]
@pavellishin sorry for the super late response. I've fixed the issues with the extension and published them a few minutes ago. v1.5 should be available on the web store sometime today.

The extension broke for a few reasons:
- Flickr's API now only accepts https requests, I was pointing at http.
- Flickr revoked the API token
- Chrome's extension platform has changed significantly, and many fixes were required.

**Comment by pavellishin** [comment]
Awesome, thanks!
